export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const EDIT_TODO = 'edit_todo'
export const MARK_TODO = 'mark_todo'
export const MARK_ALL = 'mark_all'
export const CLEAR_MARKED = 'clear_marked'